sudo: required
services:
  - docker

env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
  # Install Google Cloud cli and login/configure
  # decrypt the gcloud login credentials
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  # login with the previously decrypted credentials
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project multi-k8s-289015
  - gcloud config set compute/zone us-west2-a
  - gcloud container clusters get-credentials multi-cluster
  # login to docker (installed via the services config above)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t bradley2w1dl/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true bradley2w1dl/react-test npm test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
